name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steeps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup docekr buildx
        uses: docker/setup-buildx-action@v3

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lahiruyasas/react-movie-rating-app:latest
          build-args: |
          VITE_API_URL=${{ secrets.VITE_API_URL }}

        
